### ISSUE TITLE
Auto Tagging should create multiple tags for semver releases

### ISSUE THREAD

**Issue by jmcnevin** [go-vela/vela-docker#35]
## Description

Currently, `auto_tag`, when applied during a tag event, will simply tag the container with `BUILD_TAG`, but it would be nice if it would create a series of tags based on the tag provided, if it is recognized as a semantic version number.

Example: If `BUILD_TAG` is `v2.1.24`, the following tags would be created (the "v", if present, will be stripped):

* `2.1.24`
* `2.1`
* `2`
* `latest`

## Value

This will allow container users to "subscribe" to a particular version scope, depending on their comfort level, and receive updates without knowing exact patch numbers, for example.

## Definition of Done

The auto_tag parameter should cause tagging to behave as described above.

## Effort  (Optional)

1 day

**Comment by galacticgumshoe** [comment]
👍 Would love to see this enhancement! I'm currently doing a workaround as described here: https://target-tts.slack.com/archives/CN8N93Q6L/p1587647862121100

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
