### ISSUE TITLE
Add the ability to use the label flag

### ISSUE THREAD

**Issue by kneal** [go-vela/vela-docker#39]
## Description

_What is your idea?_

Add the ability to use the `label` flag in kaniko

Flag documentation:
https://github.com/GoogleContainerTools/kaniko/#--label

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

Customers using the docker CLI may be adding custom labels to their images the `--label` will allow us to have support for kaniko's equivalent flag.

## Definition of Done

_What is the end goal of this story?_

The flag is useable in the plugins

**Comment by jbrockopp** [comment]
https://github.com/go-vela/vela-docker/pull/44

This is complete.
