### ISSUE TITLE
Add the ability to use the registry mirror flag

### ISSUE THREAD

**Issue by kneal** [go-vela/vela-docker#40]
## Description

_What is your idea?_

Add the ability to use the `registry-mirror` flag in kaniko

Flag documentation:
https://github.com/GoogleContainerTools/kaniko#--registry-mirror

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

Allow users to pull from a different mirror other than the default `--registry-mirror`

## Definition of Done

_What is the end goal of this story?_

The flag is useable in the plugins

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
